name = "drift-bottle"
main = "src/index.ts"
compatibility_date = "2026-08-01"

workers_dev = true

routes = [
  { pattern = "driftbottle.love", custom_domain = true },
  { pattern = "www.driftbottle.love", custom_domain = true },
]

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = ["/api/*", "/b/*"]

[[d1_databases]]
binding = "DB"
database_name = "drift-bottle"
database_id = "39bf1672-7064-49d8-95ea-79e4f396b6b2"

[ai]
binding = "AI"
